import { ProjectTypes } from "@/types";
export const projectData: ProjectTypes[] = [
  {
    id: 1,
    title: "Wix Website Clone",
    deployment: "https://michellejanay-wix-clone.netlify.app",
    source_code: "https://github.com/michellejanay/responsive-grid-project",
    technologies: "HTML/CSS grid",
    image: "/images/wix-clone.png",
    gif: "/gifs/wix.gif",
  },
  {
    id: 2,
    title: "magic 8 ball",
    deployment: "https://magic-michellejanay.netlify.app",
    source_code: "https://github.com/michellejanay/magic",
    technologies: "HTML/CSS, JavaScript",
    image: "/images/magic-8-ball.png",
    gif: "/gifs/magic.gif",
  },
  {
    id: 3,
    title: "TV DOM Project",
    deployment: "https://cyf-michellejanay-tv-dom-project.netlify.app/",
    source_code: "https://github.com/michellejanay/tv-show-dom-project",
    technologies: "HTML/CSS, JavaScript, TV Maze API",
    image: "/images/tv-dom-project.png",
    gif: "/gifs/tv-dom-project.gif",
  },
  {
    id: 4,
    title: "Quote App",
    deployment: "https://michellejanay-quote-server.netlify.app/",
    source_code: "https://github.com/michellejanay/quote-app",
    technologies: "React, Node, Express, PostgreSQL, Glitch",
    image: "/images/quote-app.png",
    gif: "/gifs/quote-app.gif",
  },
  {
    id: 5,
    title: "Video App",
    deployment: "https://michellejanay-cyf-video-app.onrender.com/",
    source_code: "https://github.com/michellejanay/Video-App",
    technologies: "React, Node/Express, PostgreSQL",
    image: "/images/video-app.png",
    gif: "/gifs/video-app.gif",
  },
];
